refactor: use whiskers
catppuccin/codemirror pull request #5
Opened 2024-06-09 11:01 UTC by thelooter

Adds [Whiskers](https://github.com/catppuccin/toolbox/tree/main/whiskers), Catppuccin's in-house templating tool, to build the themes. Instead of editing the `flavor.css` files directly, edit  the `codemirror.tera` file and then run just build to build the output themes. You will need Whiskers (linked above) and optionally [Just](https://github.com/casey/just) installed.

2024-06-09 13:35 UTC, uncenter requested changes

2024-06-09 13:35 UTC, uncenter commented on codemirror.tera
> +accent: mauve
```suggestion
```

2024-06-09 13:35 UTC, uncenter commented on codemirror.tera
> +.cm-s-ctp-{{ flavor.identifier }}.CodeMirror,
```suggestion
.cm-s-ctp-{{ flavor.identifier }}.CodeMirror,
```

This line is super repetitive. I would set it to a variable like `{% set prefix = ".cm-s-ctp-" ~ flavor.identifier %}`.

2024-06-09 13:35 UTC, uncenter commented on justfile
> +  whiskers codemirror.tera
Newlines please!

2024-06-10 12:41 UTC, griimick commented
Hey! Can you also add a section in README with instructions for setting up a dev environment to build the theme with the current changes? Sorry, I am not up to date with the whiskers setup but I would like to know how to build the theme with the new build system.

2024-06-10 12:55 UTC, uncenter commented
> Hey! Can you also add a section in README with instructions for setting up a dev environment to build the theme with the current changes? Sorry, I am not up to date with the whiskers setup but I would like to know how to build the theme with the new build system.

I don't think we are opting to go with Whiskers for this port.

2024-06-10 12:55 UTC, uncenter commented
I'm going to close this for now, @griimick I can direct you to our conversation in `#dev` if needed.

2024-06-10 12:55 UTC, closed without merging